apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data
  namespace: {{ NAMESPACE }}
  labels:
    name: es-data
    component: elasticsearch
    role: data
spec:
  selector:
    matchLabels:
      component: elasticsearch
      role: data
  serviceName: elasticsearch-data
  replicas: {{ ES_DATA_NUM_PODS }}
  template:
    metadata:
      labels:
        name: es-data
        deployment: {{ DEPLOY_TO }}
        component: elasticsearch
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-data
        image: quay.io/pires/docker-elasticsearch-kubernetes:{{ ELASTICSEARCH_VERSION }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: "{{ ES_CLUSTER_NAME }}"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms{{ ELASTICSEARCH_JVM_MEMORY }} -Xmx{{ ELASTICSEARCH_JVM_MEMORY }}"
        - name: ES_PLUGINS_INSTALL
          value: "repository-gcs"  # ,mapper-size
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
        #volume.beta.kubernetes.io/storage-class: ssd-storage-class
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ ELASTICSEARCH_DISK_SIZE }}

