apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-client
  namespace: default
  labels:
    name: es-client
    component: elasticsearch
    role: client
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: es-client
        component: elasticsearch
        role: client
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-client
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: quay.io/pires/docker-elasticsearch-kubernetes:6.3.2
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: "es-cluster"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        - name: ES_PLUGINS_INSTALL
          value: "repository-gcs"  # ,mapper-size"
        - name: NETWORK_HOST   # workaround for https://github.com/pires/kubernetes-elasticsearch-cluster/issues/128
          value: "_site_,_lo_"
        #- name: DISCOVERY_SERVICE
        #  value: "elasticsearch-discovery:9300"
        #  #value: "elasticsearch-persistent-node:9300"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
