apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data-loading
  namespace: default
  labels:
    name: es-data-loading
    component: elasticsearch-loading
    role: data
spec:
  selector:
    matchLabels:
      component: elasticsearch-loading
      role: data
  serviceName: es-data-loading
  replicas: 2
  template:
    metadata:
      labels:
        name: es-data-loading
        component: elasticsearch-loading
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-data-loading
        image: quay.io/pires/docker-elasticsearch-kubernetes:6.3.2
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: "es-cluster"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms8g -Xmx8g"
        #- name: ES_PLUGINS_INSTALL
        #  value: "repository-gcs"   #,mapper-size
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
        #- name: config
        #  mountPath: /elasticsearch/config
      nodeSelector:
        #cloud.google.com/gke-nodepool: "elasticsearch"
        cloud.google.com/gke-local-ssd: "true"
      volumes:
        - name: "storage"
          hostPath:
            path: "/mnt/disks/ssd0"
        #- name: config
        #  configMap:
        #    name: elasticsearch-config