DEPLOY_TO: 'gcloud-dev'
DEPLOY_TO_PREFIX: 'gcloud'
DEPLOYMENT_TYPE: 'dev'

DOCKER_IMAGE_PREFIX: 'gcr.io/{{ GCLOUD_PROJECT }}'

# gcloud settings
#CLUSTER_NAME: 'hail-db-cluster-dev'
CLUSTER_NAME: 'seqr-cluster-dev'
CLUSTER_MACHINE_TYPE: 'n1-highmem-2'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
CLUSTER_NUM_NODES: 6

ELASTICSEARCH_NUM_DATA_PODS: 6
ELASTICSEARCH_NUM_CLIENT_PODS: 2
ELASTICSEARCH_NUM_MASTER_PODS: 3
