kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-svc
  labels:
    name: elasticsearch
    deployment: test
spec:
  type: NodePort
  ports:
  - name: elasticsearch
    port: 30001
    nodePort: 30001
  selector:
    name: elasticsearch
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch
        deployment: test
    spec:
      volumes:
      - name: elasticsearch-dbpath
        gcePersistentDisk:
          # This disk must already exist.
          pdName: test-elasticsearch-disk
          fsType: ext4
      containers:
      - name: elasticsearch-pod
        image: gcr.io/seqr-project/elasticsearch
        ports:
        - containerPort: 30001
          protocol: TCP
        imagePullPolicy: Always
        volumeMounts:
        - name: elasticsearch-dbpath
          mountPath: /elasticsearch-data
        env:
        - name: ELASTICSEARCH_PORT
          value: "30001"
      restartPolicy: Always
      dnsPolicy: ClusterFirst
